---
name: Docker build
on:
  create:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.previoustag.outputs.tag }}

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tomonorimatsumura/redmine_theme_kodomo_midori
          tags: ${{ steps.previoustag.outputs.tag }}
